### ISSUE TITLE
yam strips empty structs

### ISSUE THREAD

**Issue by imjasonh** [chainguard-dev/yam#79]
Input:

```
update:
  enabled: true
  git: {}
```

`yam that.yaml` produces

```
update:
  enabled: true
  git:
```

These are different values; in Go, this would be the difference between `nil` and a pointer to an empty struct.

**Comment by luhring** [comment]
I feel like this came up once before and @rawlingsj and I solved it somehow... 🤔

**Comment by rawlingsj** [comment]
Hmm yeah - wonder if yam is up to date?  This was @luhring fix that resolved it from memory https://github.com/chainguard-dev/yam/pull/66

**Comment by rawlingsj** [comment]
There's a test case too https://github.com/chainguard-dev/yam/blob/3eba0a7cdfc15e2f97336dad564dfed9b75a3883/pkg/yam/testdata/format/update_expected.yaml#L3. Hopefully this is just an out of date yam? 🤞

**Comment by imjasonh** [comment]
Yep! 🤦
